language: node_js

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      env: CI_BUILD_TYPE=default
      node_js: 10
      services:
        - xvfb
      addons:
        chrome: stable
      before_install:
        - export DISPLAY=:99.0
        - yarn global add @chialab/rna-cli
        - yarn install
      script:
        - rna unit --coverage --browser
    - stage: test
      node_js: 10
      env: CI_BUILD_TYPE=saucelabs
      before_install:
        - yarn global add @chialab/rna-cli
        - yarn install
      script:
        - rna unit --saucelabs --context './test/context.html'
  allow_failures:
    - env: "CI_BUILD_TYPE=saucelabs"

after_success:
  - npm install -g codecov
  - cat reports/unit/coverage/*/lcov.info | codecov
