language: node_js

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      node_js: 8
      env: CI_BUILD_TYPE=default
      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - npm install git+https://gitlab.com/chialab/rna-cli -g
      script:
        - rna unit
    - stage: test
      node_js: 8
      env: CI_BUILD_TYPE=saucelabs
      before_install:
        - npm install git+https://gitlab.com/chialab/rna-cli -g
      script:
        - rna unit --saucelabs
  allow_failures:
    - env: "CI_BUILD_TYPE=saucelabs"
